server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: ziggo-assignment
  datasource:
    url: jdbc:h2:mem:ziggodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  main:
    lazy-initialization: true

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true

ziggo:
  url:
    user-url: https://reqres.in/api/users?page={page}

logging:
  level:
    nl:
      vodafoneziggo: DEBUG